version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    restart: always
    environment: 
      ES_JAVA_OPTS: "-Xms1g -Xmx4g"
    ports:
      - "172.17.0.1:9200:9200"  
    command:
      - sh
      - -c
      - " ./bin/elasticsearch-plugin install --batch analysis-icu;
      ./bin/elasticsearch"
    volumes:
      - "./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
      - "./data:/usr/share/elasticsearch/data"
    user: 1000:1000
    ulimits:
      memlock:
        soft: -1
        hard: -1
    
  nginx:
    image: nginx:latest
    depends_on:
      - elasticsearch
    volumes:
      - "./config/nginx.conf:/etc/nginx/nginx.conf"
      - "./config/.htpasswd:/etc/nginx/.htpasswd"
    ports:
      - "80:80"
      - "443:443"
    restart: always
